#!/bin/bash

source `dirname $0`/helpers/assert.sh
source `dirname $0`/helpers/test_runner.sh

# --- format_time ---

test_format_time_no_seconds() {
	actual=$(format_time 23)
	assert_equal "00:00" "${actual}"
}

test_format_time_minutes() {
	actual=$(format_time 61)
	assert_equal "00:01" "${actual}"
}

test_format_time_minutes_double_digit() {
	actual=$(format_time 1260)
	assert_equal "00:21" "${actual}"
}

test_format_time_hours_and_minutes() {
	actual=$(format_time 3900)
	assert_equal "01:05" "${actual}"
}

# --- average ----

test_average_one_value() {
	actual=$(average 100)
	assert_equal "100" "${actual}"
}

test_average_three_values() {
	input=$(printf "23\n52\n24\n")
	actual=$(average $input)
	assert_equal "33" "${actual}"
}

test_average_odd_average_is_even() {
	input=$(printf "3\n2\n")
	actual=$(average $input)
	assert_equal "2" "${actual}"
}

test_average_filters_out_zeros() {
	input=$(printf "3\n0\n3\n")
	actual=$(average $input)
	assert_equal "3" "${actual}"
}

source `dirname $0`/../scripts/helpers.sh

run_tests \
	test_format_time_no_seconds \
	test_format_time_minutes \
	test_format_time_minutes_double_digit \
	test_format_time_hours_and_minutes \
	\
	test_average_one_value \
	test_average_three_values \
	test_average_odd_average_is_even \
	test_average_filters_out_zeros
